### ISSUE TITLE
Missing translation files. Yarn start fails.

### ISSUE THREAD

**Issue by ToniTepes** [easherma/cct-small-business#6]
Whenever I run yarn start I get an error that this file is missing `/src/intl/en.json`

Possibly you forgot to add it from your local?

**Comment by easherma** [comment]
Ahh, looks like the intl plugin didn't like being added without having anything to reference. 

I've removed it for now. 

Also, lets stick to using npm for this project if you don't mind. Just running ```gatsby develop``` or ```npm run start``` should work, assuming you've run ```npm install```.
